### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m1-evaluacion-intermedia-veroena#1]
Really cool job @veroena !!!
Here you have some tips to improve the exercise:

- [x] Fix the language and the meta title of the page
- [x] We need an H1 tag (better than a P tag)
- [x] Humanize text in `alt` attributes, a sentence without the underscore may do the trick.
- [x] Move the font CSS before your main CSS
- [x] There are some weird margins, let's remove them: Remember the browser add some margins to the `<body>` element; and Any time we set an absolute or fixed position on an HTML element we should also set a left/right and a top/bottom CSS properties so it will display properly
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)
- [x] Main title should be vertically and horizontally centered (should we use Flex to achieve this?)
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles

Let me know if you have any doubts ;)

Go for it!!

**Comment by veroena** [comment]
Thanks for the tips! I think I ticked them all, I'm going to look at the solutions you posted now :)

**Comment by oneeyedman** [comment]
Good job @veroena!

Some things need to be fixed:

- [ ] The Main element has a top-padding that make the vertical scroll bar to appear.
- [ ] The main title font size should be applied to the H1 tag because it shows a proportional font size of its container by default.

**Comment by veroena** [comment]
Thank you! It took me a while to see the padding-top... Won't forget again!
